from __future__ import annotations

from sqlalchemy import (
    Boolean,
    Column,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    Numeric,
    PrimaryKeyConstraint,
    String,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB


metadata = MetaData()

reference_versions = Table(
    "reference_versions",
    metadata,
    Column("reference_key", String(120), primary_key=True),
    Column("version", String(120), nullable=False),
    Column("effective_from", String(40), nullable=False),
)

app_settings = Table(
    "app_settings",
    metadata,
    Column("setting_key", String(120), primary_key=True),
    Column("value_json", JSONB, nullable=False),
)

users = Table(
    "users",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("username", String(120), nullable=False, unique=True),
    Column("email", String(255), nullable=False),
    Column("role", String(120), nullable=False),
    Column("status", String(40), nullable=False),
    Column("password", String(255), nullable=False),
    Column("created_at", String(40), nullable=False),
)

patients = Table(
    "patients",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(255), nullable=False),
    Column("mrn", String(120), nullable=False, unique=True),
    Column("dob", String(40), nullable=False),
    Column("sex", String(20), nullable=False),
    Column("email", String(255), nullable=False),
    Column("phone", String(120), nullable=False),
    Column("status", String(40), nullable=False),
    Column("created_at", String(40), nullable=False),
)

providers = Table(
    "providers",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(255), nullable=False),
    Column("npi", String(120), nullable=False, unique=True),
    Column("practice_number", String(120), nullable=False, unique=True),
    Column("specialty", String(120), nullable=False),
    Column("discipline", String(120), nullable=False),
    Column("is_dsp_provider", Boolean, nullable=False, default=True),
    Column("email", String(255), nullable=False),
    Column("phone", String(120), nullable=False),
    Column("status", String(40), nullable=False),
    Column("created_at", String(40), nullable=False),
)

claims = Table(
    "claims",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("version", Integer, nullable=False),
    Column("previous_version", Integer),
    Column("scenario_key", String(120), nullable=False),
    Column("status", String(80), nullable=False),
    Column("claim_number", String(120), nullable=False, unique=True),
    Column("claim_reference", String(120), nullable=False, unique=True),
    Column("invoice_number", String(120), nullable=False),
    Column("scheme_id", String(120), nullable=False),
    Column("plan_option_id", String(120), nullable=False),
    Column("member_number", String(120), nullable=False),
    Column("patient_id", Integer, ForeignKey("patients.id"), nullable=False),
    Column("provider_id", Integer, ForeignKey("providers.id"), nullable=False),
    Column("service_date", String(40), nullable=False),
    Column("pmb_status", String(80), nullable=False),
    Column("readiness_status", String(80), nullable=False),
    Column("validation_status", String(80), nullable=False),
    Column("payload_status", String(80), nullable=False),
    Column("submission_status", String(80), nullable=False),
    Column("submission_channel", String(40)),
    Column("remittance_status", String(80), nullable=False),
    Column("reconciliation_status", String(80), nullable=False),
    Column("latest_snapshot_id", String(120)),
    Column("latest_payload_id", String(120)),
    Column("latest_submission_id", String(120)),
    Column("latest_response_id", String(120)),
    Column("latest_financial_bundle_id", String(120)),
    Column("latest_remittance_id", String(120)),
    Column("latest_reconciliation_id", String(120)),
    Column("latest_pmb_decision_id", String(120)),
    Column("latest_benefit_route_decision_id", String(120)),
    Column("latest_costing_preview_id", String(120)),
    Column("created_at", String(40), nullable=False),
    Column("updated_at", String(40), nullable=False),
    Column("payload_json", JSONB, nullable=False),
)
Index("ix_claims_status", claims.c.status)

claim_drafts = Table(
    "claim_drafts",
    metadata,
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("draft_json", JSONB, nullable=False),
    Column("updated_at", String(40), nullable=False),
    PrimaryKeyConstraint("claim_id"),
)

claim_versions = Table(
    "claim_versions",
    metadata,
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("version", Integer, nullable=False),
    Column("snapshot_id", String(120)),
    Column("status", String(80), nullable=False),
    Column("previous_version", Integer),
    Column("change_summary", Text, nullable=False),
    Column("data_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
    PrimaryKeyConstraint("claim_id", "version"),
)

billing_snapshots = Table(
    "billing_snapshots",
    metadata,
    Column("snapshot_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("data_json", JSONB, nullable=False),
    Column("input_hash", String(255), nullable=False),
    Column("created_at", String(40), nullable=False),
    Column("created_by", String(120), nullable=False),
    UniqueConstraint("claim_id", "claim_version", name="uq_billing_snapshots_claim_version"),
)
Index("ix_billing_snapshots_claim_version", billing_snapshots.c.claim_id, billing_snapshots.c.claim_version, unique=True)

rule_definitions = Table(
    "rule_definitions",
    metadata,
    Column("rule_id", String(120), primary_key=True),
    Column("name", String(255), nullable=False),
    Column("category", String(120), nullable=False),
    Column("severity", String(20), nullable=False),
    Column("reason_code", String(120), nullable=False),
    Column("message", Text, nullable=False),
    Column("remediation_hint", Text, nullable=False),
    Column("affected_fields_json", JSONB, nullable=False),
    Column("stage_scope_json", JSONB, nullable=False),
    Column("enabled", Boolean, nullable=False, default=True),
    Column("decision_table_json", JSONB, nullable=False),
)

policy_profiles = Table(
    "policy_profiles",
    metadata,
    Column("policy_profile_id", String(120), nullable=False),
    Column("version", Integer, nullable=False),
    Column("scheme_id", String(120), nullable=False),
    Column("plan_option_id", String(120), nullable=False),
    Column("effective_from", String(40), nullable=False),
    Column("effective_to", String(40)),
    Column("status", String(40), nullable=False),
    Column("approved_by", String(120)),
    Column("approved_at", String(40)),
    Column("runtime_toggles_json", JSONB, nullable=False),
    Column("rule_ids_json", JSONB, nullable=False),
    PrimaryKeyConstraint("policy_profile_id", "version"),
)

decision_bundles = Table(
    "decision_bundles",
    metadata,
    Column("decision_bundle_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("snapshot_id", String(120)),
    Column("stage", String(80), nullable=False),
    Column("policy_profile_id", String(120), nullable=False),
    Column("policy_version", Integer, nullable=False),
    Column("outcome", String(20), nullable=False),
    Column("input_hash", String(255), nullable=False),
    Column("payload_hash", String(255)),
    Column("reference_versions_json", JSONB, nullable=False),
    Column("rule_hits_json", JSONB, nullable=False),
    Column("explanations_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
    Column("created_by", String(120), nullable=False),
)

readiness_runs = Table(
    "readiness_runs",
    metadata,
    Column("readiness_run_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("decision_bundle_id", String(120), ForeignKey("decision_bundles.decision_bundle_id"), nullable=False),
    Column("outcome", String(20), nullable=False),
    Column("items_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
)

icd10_reference = Table(
    "icd10_reference",
    metadata,
    Column("code", String(20), primary_key=True),
    Column("description", Text, nullable=False),
    Column("version", String(120), nullable=False),
    Column("active", Boolean, nullable=False, default=True),
    Column("effective_from", String(40), nullable=False),
    Column("effective_to", String(40)),
    Column("source", String(255), nullable=False),
    Column("status", String(40), nullable=False),
)

pmb_conditions = Table(
    "pmb_conditions",
    metadata,
    Column("condition_id", String(120), primary_key=True),
    Column("name", Text, nullable=False),
    Column("type", String(40), nullable=False),
    Column("descriptor", Text, nullable=False),
    Column("category", String(120), nullable=False),
    Column("metadata_json", JSONB, nullable=False),
    Column("evidence_requirements_json", JSONB, nullable=False),
    Column("confirmation_flags_json", JSONB, nullable=False),
    Column("active", Boolean, nullable=False, default=True),
    Column("effective_from", String(40), nullable=False),
    Column("effective_to", String(40)),
    Column("source", String(255), nullable=False),
    Column("status", String(40), nullable=False),
)

icd10_pmb_mappings = Table(
    "icd10_pmb_mappings",
    metadata,
    Column("mapping_id", String(120), primary_key=True),
    Column("icd10_code", String(20), ForeignKey("icd10_reference.code"), nullable=False),
    Column("pmb_condition_id", String(120), ForeignKey("pmb_conditions.condition_id"), nullable=False),
    Column("match_type", String(20), nullable=False),
    Column("version", Integer, nullable=False),
    Column("effective_from", String(40), nullable=False),
    Column("effective_to", String(40)),
    Column("confidence", String(20), nullable=False),
    Column("auto_route_allowed", Boolean, nullable=False, default=False),
    Column("required_evidence_types_json", JSONB, nullable=False),
    Column("active", Boolean, nullable=False, default=True),
    Column("status", String(40), nullable=False),
    Column("source", String(255), nullable=False),
)
Index(
    "ix_icd10_pmb_mappings_lookup",
    icd10_pmb_mappings.c.icd10_code,
    icd10_pmb_mappings.c.active,
    icd10_pmb_mappings.c.effective_from,
    icd10_pmb_mappings.c.effective_to,
)

benefit_route_rules = Table(
    "benefit_route_rules",
    metadata,
    Column("rule_id", String(120), primary_key=True),
    Column("scheme_id", String(120), nullable=False),
    Column("plan_option_id", String(120), nullable=False),
    Column("route_when_confirmed", String(80), nullable=False),
    Column("route_when_possible", String(80), nullable=False),
    Column("route_when_missing_evidence", String(80), nullable=False),
    Column("auto_route_possible_matches", Boolean, nullable=False, default=False),
    Column("active", Boolean, nullable=False, default=True),
    Column("effective_from", String(40), nullable=False),
    Column("effective_to", String(40)),
    Column("source", String(255), nullable=False),
)

tariff_rates = Table(
    "tariff_rates",
    metadata,
    Column("rate_id", String(120), primary_key=True),
    Column("scheme_id", String(120), nullable=False),
    Column("plan_option_id", String(120), nullable=False),
    Column("tariff_code", String(120), nullable=False),
    Column("dsp_flag", Boolean, nullable=False, default=True),
    Column("rate_amount", Numeric(12, 2), nullable=False),
    Column("unit", String(40), nullable=False),
    Column("active", Boolean, nullable=False, default=True),
    Column("effective_from", String(40), nullable=False),
    Column("effective_to", String(40)),
    Column("source", String(255), nullable=False),
)

pmb_payment_policies = Table(
    "pmb_payment_policies",
    metadata,
    Column("policy_id", String(120), primary_key=True),
    Column("scheme_id", String(120), nullable=False),
    Column("plan_option_id", String(120), nullable=False),
    Column("pay_in_full_requires_dsp", Boolean, nullable=False, default=True),
    Column("voluntary_non_dsp_rate_mode", String(40), nullable=False),
    Column("involuntary_non_dsp_no_copay", Boolean, nullable=False, default=True),
    Column("active", Boolean, nullable=False, default=True),
    Column("effective_from", String(40), nullable=False),
    Column("effective_to", String(40)),
    Column("source", String(255), nullable=False),
)

claim_diagnoses = Table(
    "claim_diagnoses",
    metadata,
    Column("diagnosis_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("seq", Integer, nullable=False),
    Column("icd10_code", String(20), ForeignKey("icd10_reference.code"), nullable=False),
    Column("is_primary", Boolean, nullable=False, default=False),
    Column("source", String(120), nullable=False),
    Column("captured_by", String(120), nullable=False),
    Column("captured_at", String(40), nullable=False),
)
Index("ix_claim_diagnoses_claim_primary", claim_diagnoses.c.claim_id, claim_diagnoses.c.is_primary)

claim_line_items = Table(
    "claim_line_items",
    metadata,
    Column("claim_line_item_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("line_id", String(120), nullable=False),
    Column("service_code", String(120), nullable=False),
    Column("service_description", Text, nullable=False),
    Column("quantity", Numeric(12, 2), nullable=False),
    Column("unit_price", Numeric(12, 2), nullable=False),
    Column("claimed_amount", Numeric(12, 2), nullable=False),
    Column("service_date", String(40), nullable=False),
    Column("modifiers_json", JSONB, nullable=False),
    Column("nappi_code", String(120)),
    Column("device_id", String(120)),
    Column("rendering_provider_practice_number", String(120)),
    Column("requires_preauth", Boolean, nullable=False, default=False),
    Column("requires_attachment", Boolean, nullable=False, default=False),
    UniqueConstraint("claim_id", "claim_version", "line_id", name="uq_claim_line_items_claim_version_line"),
)
Index("ix_claim_line_items_claim_version", claim_line_items.c.claim_id, claim_line_items.c.claim_version)

claim_line_diagnosis_links = Table(
    "claim_line_diagnosis_links",
    metadata,
    Column("link_id", String(120), primary_key=True),
    Column("claim_line_item_id", String(120), ForeignKey("claim_line_items.claim_line_item_id"), nullable=False),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("line_id", String(120), nullable=False),
    Column("diagnosis_id", String(120), ForeignKey("claim_diagnoses.diagnosis_id"), nullable=False),
    Column("sequence", Integer, nullable=False),
    UniqueConstraint("claim_line_item_id", "diagnosis_id", name="uq_claim_line_diagnosis_link"),
)

claim_documents = Table(
    "claim_documents",
    metadata,
    Column("document_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("encounter_id", String(120)),
    Column("patient_id", Integer, ForeignKey("patients.id"), nullable=False),
    Column("provider_id", Integer, ForeignKey("providers.id"), nullable=False),
    Column("doc_type", String(80), nullable=False),
    Column("filename", String(255), nullable=False),
    Column("storage_ref", String(255), nullable=False),
    Column("file_hash", String(255), nullable=False),
    Column("uploaded_at", String(40), nullable=False),
    Column("uploaded_by", String(120), nullable=False),
    Column("status", String(40), nullable=False, default="AVAILABLE"),
)
Index("ix_claim_documents_claim_version", claim_documents.c.claim_id, claim_documents.c.claim_version)

pmb_decisions = Table(
    "pmb_decisions",
    metadata,
    Column("decision_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("stage", String(80), nullable=False),
    Column("pmb_status", String(40), nullable=False),
    Column("matched_icd10", String(20)),
    Column("mapping_id", String(120)),
    Column("condition_id", String(120)),
    Column("condition_name", String(255)),
    Column("condition_type", String(40)),
    Column("provider_marked_pmb", Boolean, nullable=False, default=False),
    Column("auto_flagged", Boolean, nullable=False, default=False),
    Column("reason_code", String(120), nullable=False),
    Column("message", Text, nullable=False),
    Column("remediation_hint", Text, nullable=False),
    Column("explainability", Text, nullable=False),
    Column("descriptor", Text),
    Column("confidence", String(20), nullable=False),
    Column("evidence_required_json", JSONB, nullable=False),
    Column("evidence_missing_json", JSONB, nullable=False),
    Column("evaluated_icd10_list_json", JSONB, nullable=False),
    Column("mapping_table_version", String(255)),
    Column("effective_date_used", String(40)),
    Column("detection_reason", String(120)),
    Column("action_json", JSONB),
    Column("line_level_evaluation_limited", Boolean, nullable=False, default=False),
    Column("created_at", String(40), nullable=False),
)

benefit_routing_decisions = Table(
    "benefit_routing_decisions",
    metadata,
    Column("decision_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("stage", String(80), nullable=False),
    Column("pmb_decision_id", String(120), ForeignKey("pmb_decisions.decision_id")),
    Column("pmb_status", String(40), nullable=False),
    Column("trigger_icd10", String(20)),
    Column("mapping_id", String(120)),
    Column("pmb_condition_id", String(120)),
    Column("provider_marked_pmb", Boolean, nullable=False, default=False),
    Column("pmb_detected", Boolean, nullable=False, default=False),
    Column("route", String(80), nullable=False),
    Column("action", String(80), nullable=False),
    Column("confidence", String(20), nullable=False),
    Column("reason_code", String(120), nullable=False),
    Column("message", Text, nullable=False),
    Column("remediation_hint", Text, nullable=False),
    Column("evidence_required_json", JSONB, nullable=False),
    Column("evidence_missing_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
)

costing_previews = Table(
    "costing_previews",
    metadata,
    Column("preview_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("stage", String(80), nullable=False),
    Column("pmb_decision_id", String(120), ForeignKey("pmb_decisions.decision_id")),
    Column("routing_decision_id", String(120), ForeignKey("benefit_routing_decisions.decision_id")),
    Column("claimed_total", Numeric(12, 2), nullable=False),
    Column("allowed_total", Numeric(12, 2), nullable=False),
    Column("pmb_allowed_total", Numeric(12, 2)),
    Column("member_liability_estimate", Numeric(12, 2), nullable=False),
    Column("pricing_basis", String(80), nullable=False),
    Column("pending_pmb_review", Boolean, nullable=False, default=False),
    Column("provisional", Boolean, nullable=False, default=False),
    Column("reason_code", String(120), nullable=False),
    Column("explanation", Text, nullable=False),
    Column("created_at", String(40), nullable=False),
)

payloads = Table(
    "payloads",
    metadata,
    Column("payload_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("snapshot_id", String(120), ForeignKey("billing_snapshots.snapshot_id"), nullable=False),
    Column("canonical_claim_json", JSONB, nullable=False),
    Column("pseudo_edi", Text, nullable=False),
    Column("phisc_xml", Text, nullable=False),
    Column("canonical_hash", String(255), nullable=False),
    Column("payload_hash", String(255), nullable=False),
    Column("created_at", String(40), nullable=False),
)

edi_artifacts = Table(
    "edi_artifacts",
    metadata,
    Column("artifact_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("payload_id", String(120), ForeignKey("payloads.payload_id")),
    Column("format", String(40), nullable=False),
    Column("content", Text, nullable=False),
    Column("content_hash", String(255), nullable=False),
    Column("validation_errors_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
    Column("created_by", String(120), nullable=False),
)

submissions = Table(
    "submissions",
    metadata,
    Column("submission_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("channel", String(40), nullable=False),
    Column("correlation_id", String(120), nullable=False),
    Column("idempotency_key", String(255), nullable=False),
    Column("status", String(40), nullable=False),
    Column("attempts", Integer, nullable=False),
    Column("created_at", String(40), nullable=False),
    Column("updated_at", String(40), nullable=False),
    UniqueConstraint("idempotency_key", name="uq_submissions_idempotency_key"),
)

transport_logs = Table(
    "transport_logs",
    metadata,
    Column("transport_log_id", String(120), primary_key=True),
    Column("submission_id", String(120), ForeignKey("submissions.submission_id")),
    Column("claim_id", Integer, ForeignKey("claims.id")),
    Column("claim_version", Integer),
    Column("artifact_id", String(120), ForeignKey("edi_artifacts.artifact_id")),
    Column("event", String(120), nullable=False),
    Column("details_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
)

responses = Table(
    "responses",
    metadata,
    Column("response_id", String(120), primary_key=True),
    Column("submission_id", String(120), ForeignKey("submissions.submission_id"), nullable=False),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("status", String(20), nullable=False),
    Column("reasons_json", JSONB, nullable=False),
    Column("received_at", String(40), nullable=False),
)

financial_bundles = Table(
    "financial_bundles",
    metadata,
    Column("financial_bundle_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("policy_profile_id", String(120), nullable=False),
    Column("policy_version", Integer, nullable=False),
    Column("totals_json", JSONB, nullable=False),
    Column("line_outcomes_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
)

remittances = Table(
    "remittances",
    metadata,
    Column("remittance_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("payment_batch_ref", String(120), nullable=False),
    Column("claim_reference", String(120), nullable=False),
    Column("lines_json", JSONB, nullable=False),
    Column("totals_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
)

reconciliations = Table(
    "reconciliations",
    metadata,
    Column("reconciliation_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("status", String(40), nullable=False),
    Column("exception_reasons_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
)

reconciliation_exceptions = Table(
    "reconciliation_exceptions",
    metadata,
    Column("exception_id", String(120), primary_key=True),
    Column("reconciliation_id", String(120), ForeignKey("reconciliations.reconciliation_id"), nullable=False),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("reason_code", String(120), nullable=False),
    Column("message", Text, nullable=False),
    Column("created_at", String(40), nullable=False),
)

ledger_entries = Table(
    "ledger_entries",
    metadata,
    Column("entry_id", String(120), primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("claim_version", Integer, nullable=False),
    Column("entry_type", String(120), nullable=False),
    Column("amount", Numeric(12, 2), nullable=False),
    Column("reference", String(120), nullable=False),
    Column("detail_json", JSONB, nullable=False),
    Column("created_at", String(40), nullable=False),
)

payments = Table(
    "payments",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("claim_id", Integer, ForeignKey("claims.id"), nullable=False),
    Column("amount", Numeric(12, 2), nullable=False),
    Column("payment_date", String(40), nullable=False),
    Column("method", String(80), nullable=False),
    Column("status", String(40), nullable=False),
    Column("created_at", String(40), nullable=False),
)

audit_events = Table(
    "audit_events",
    metadata,
    Column("audit_event_id", String(120), primary_key=True),
    Column("event_type", String(120), nullable=False),
    Column("actor", String(120), nullable=False),
    Column("role", String(120), nullable=False),
    Column("entity_type", String(120), nullable=False),
    Column("entity_id", String(120), nullable=False),
    Column("policy_profile_id", String(120)),
    Column("policy_version", Integer),
    Column("hashes_json", JSONB, nullable=False),
    Column("detail_json", JSONB, nullable=False),
    Column("timestamp", String(40), nullable=False),
)

reports = Table(
    "reports",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String(255), nullable=False),
    Column("report_type", String(120), nullable=False),
    Column("generated_at", String(40), nullable=False),
    Column("period", String(120), nullable=False),
    Column("summary_json", JSONB, nullable=False),
)

ALL_TABLES = [
    reference_versions,
    app_settings,
    users,
    patients,
    providers,
    claims,
    claim_drafts,
    claim_versions,
    billing_snapshots,
    rule_definitions,
    policy_profiles,
    decision_bundles,
    readiness_runs,
    icd10_reference,
    pmb_conditions,
    icd10_pmb_mappings,
    benefit_route_rules,
    tariff_rates,
    pmb_payment_policies,
    claim_diagnoses,
    claim_line_items,
    claim_line_diagnosis_links,
    claim_documents,
    pmb_decisions,
    benefit_routing_decisions,
    costing_previews,
    payloads,
    edi_artifacts,
    submissions,
    transport_logs,
    responses,
    financial_bundles,
    remittances,
    reconciliations,
    reconciliation_exceptions,
    ledger_entries,
    payments,
    audit_events,
    reports,
]

TRUNCATE_TABLES = [
    reconciliation_exceptions,
    ledger_entries,
    reports,
    audit_events,
    payments,
    reconciliations,
    remittances,
    financial_bundles,
    responses,
    transport_logs,
    submissions,
    payloads,
    costing_previews,
    benefit_routing_decisions,
    pmb_decisions,
    claim_diagnoses,
    pmb_payment_policies,
    tariff_rates,
    benefit_route_rules,
    icd10_pmb_mappings,
    pmb_conditions,
    icd10_reference,
    claim_line_diagnosis_links,
    claim_line_items,
    claim_documents,
    readiness_runs,
    decision_bundles,
    policy_profiles,
    rule_definitions,
    billing_snapshots,
    claim_versions,
    claim_drafts,
    claims,
    providers,
    patients,
    users,
    app_settings,
    reference_versions,
]
