from __future__ import annotations

from typing import Dict


ICD10_REFERENCE_KEY = "icd10_mit"
ICD10_REFERENCE_VERSION = "DEVSEED-ICD10-CM-2026.1"
ICD10_REFERENCE_EFFECTIVE_FROM = "2025-10-01"
ICD10_REFERENCE_SOURCE = (
    "Development starter ICD-10 reference catalog aligned to CMS/CDC ICD-10-CM public materials. "
    "Not a full South African MIT code set; replace with business-owned MIT import for production."
)


ICD10_STARTER_CODES: Dict[str, str] = {
    "A09": "Infectious gastroenteritis and colitis, unspecified",
    "B18.2": "Chronic viral hepatitis C",
    "B20": "Human immunodeficiency virus disease",
    "B34.9": "Viral infection, unspecified",
    "C34.90": "Malignant neoplasm of unspecified part of unspecified bronchus or lung",
    "C50.9": "Malignant neoplasm of breast, unspecified",
    "D50.9": "Iron deficiency anaemia, unspecified",
    "D64.9": "Anaemia, unspecified",
    "E03.9": "Hypothyroidism, unspecified",
    "E05.90": "Thyrotoxicosis, unspecified, without thyrotoxic crisis or storm",
    "E11.9": "Type 2 diabetes mellitus without complications",
    "E11.65": "Type 2 diabetes mellitus with hyperglycaemia",
    "E66.9": "Obesity, unspecified",
    "E78.0": "Pure hypercholesterolaemia",
    "E78.5": "Hyperlipidaemia, unspecified",
    "F32.9": "Major depressive disorder, single episode, unspecified",
    "F41.1": "Generalised anxiety disorder",
    "F43.10": "Post-traumatic stress disorder, unspecified",
    "G43.909": "Migraine, unspecified, not intractable, without status migrainosus",
    "G47.00": "Insomnia, unspecified",
    "G56.00": "Carpal tunnel syndrome, unspecified upper limb",
    "H10.9": "Conjunctivitis, unspecified",
    "H52.4": "Presbyopia",
    "I10": "Essential hypertension",
    "I11.0": "Hypertensive heart disease with heart failure",
    "I20.9": "Angina pectoris, unspecified",
    "I21.9": "Acute myocardial infarction, unspecified",
    "I25.10": "Atherosclerotic heart disease of native coronary artery without angina pectoris",
    "I48.91": "Unspecified atrial fibrillation",
    "I50.9": "Heart failure, unspecified",
    "I63.9": "Cerebral infarction, unspecified",
    "J00": "Acute nasopharyngitis",
    "J02.9": "Acute pharyngitis, unspecified",
    "J06.9": "Acute upper respiratory infection, unspecified",
    "J11.1": "Influenza with other respiratory manifestations",
    "J18.9": "Pneumonia, unspecified organism",
    "J20.9": "Acute bronchitis, unspecified",
    "J30.9": "Allergic rhinitis, unspecified",
    "J35.03": "Chronic tonsillitis and adenoiditis",
    "J44.9": "Chronic obstructive pulmonary disease, unspecified",
    "J45.909": "Unspecified asthma, uncomplicated",
    "K02.9": "Dental caries, unspecified",
    "K04.7": "Periapical abscess without sinus",
    "K21.0": "Gastro-oesophageal reflux disease with oesophagitis",
    "K25.9": "Gastric ulcer, unspecified as acute or chronic, without haemorrhage or perforation",
    "K29.70": "Gastritis, unspecified, without bleeding",
    "K35.80": "Acute appendicitis without perforation or abscess",
    "K52.9": "Noninfective gastroenteritis and colitis, unspecified",
    "K59.00": "Constipation, unspecified",
    "K80.20": "Calculus of gallbladder without cholecystitis without obstruction",
    "K92.1": "Melaena",
    "L20.9": "Atopic dermatitis, unspecified",
    "L29.9": "Pruritus, unspecified",
    "L50.0": "Allergic urticaria",
    "M06.9": "Rheumatoid arthritis, unspecified",
    "M17.11": "Primary osteoarthritis, right knee",
    "M17.12": "Primary osteoarthritis, left knee",
    "M25.561": "Pain in right knee",
    "M25.562": "Pain in left knee",
    "M54.2": "Cervicalgia",
    "M54.5": "Low back pain",
    "M79.10": "Myalgia, unspecified site",
    "M81.0": "Age-related osteoporosis without current pathological fracture",
    "N18.3": "Chronic kidney disease, stage 3",
    "N39.0": "Urinary tract infection, site not specified",
    "N40.0": "Benign prostatic hyperplasia without lower urinary tract symptoms",
    "N94.3": "Premenstrual tension syndrome",
    "O80": "Encounter for full-term uncomplicated delivery",
    "R05.9": "Cough, unspecified",
    "R07.9": "Chest pain, unspecified",
    "R10.9": "Abdominal pain, unspecified",
    "R11.2": "Nausea with vomiting, unspecified",
    "R50.9": "Fever, unspecified",
    "R51.9": "Headache, unspecified",
    "S39.012A": "Strain of muscle, fascia and tendon of lower back, initial encounter",
    "S72.0": "Fracture of neck of femur",
    "T14.90": "Injury, unspecified",
    "Z00.0": "General adult medical examination",
    "Z00.00": "Encounter for general adult medical examination without abnormal findings",
    "Z01.818": "Encounter for other preprocedural examination",
    "Z12.11": "Encounter for screening for malignant neoplasm of colon",
    "Z23": "Encounter for immunisation",
    "Z79.4": "Long term current use of insulin",
}
